export type ParentCategory =
  | "전체"
  | "싱크대 수리"
  | "싱크대 리폼"
  | "가죽 리폼"
  | "소파 복원";

export type CaseCategory =
  | "전체"
  | "싱크대 수리"
  | "상부장 처짐"
  | "하부장 밑판 교체"
  | "싱크대 리폼"
  | "가죽 리폼"
  | "소파 복원";

export interface CaseItem {
  id: string;
  category: CaseCategory; // 세부 카테고리 (슬라이더 필터 등에 사용)
  parentCategory: ParentCategory; // 부모 카테고리 (탭 필터에 사용)
  title: string;
  region: string;
  summary: string;
  beforeImg: string;
  afterImg: string;
  blogUrl: string;
  date: string;
  tags: string[];
}

export const PARENT_CATEGORIES: ParentCategory[] = [
  "전체",
  "싱크대 수리",
  "싱크대 리폼",
  "가죽 리폼",
  "소파 복원",
];

// 부모 카테고리별 서브카테고리 정의
export const SUB_CATEGORIES: Partial<Record<ParentCategory, CaseCategory[]>> = {
  "싱크대 수리": ["상부장 처짐", "하부장 밑판 교체"],
};

// 하위 호환용
export const CASE_CATEGORIES: CaseCategory[] = [
  "전체",
  "싱크대 수리",
  "상부장 처짐",
  "하부장 밑판 교체",
  "싱크대 리폼",
  "가죽 리폼",
  "소파 복원",
];

export const cases: CaseItem[] = [
  // ─── 신규 추가 ───────────────────────────────────────────
  {
    id: "case-043",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 청라 싱크대 도어 상하부장 문짝 교체 리폼 사례",
    region: "청라",
    summary:
      "오랜된 문짝 교체 리폼 사례, pet 마감으로 제로조인트로 깔끔하게 리폼. 상부장과 하부장 모두 교체로 새 주방 느낌 완성!",
    beforeImg: "/images/cases/case-043-before.jpg",
    afterImg: "/images/cases/case-043-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224306662990",
    date: "2026-06-05",
    tags: ["싱크대 문짝 교체", "싱크대 리폼", "주방 리폼"],
  },
  {
    id: "case-042",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "인천 검단 상부장 수리 사례",
    region: "검단",
    summary: "인천 검단 상부장 수리 사례",
    beforeImg: "/images/cases/case-042-before.jpg",
    afterImg: "/images/cases/case-042-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224206983682",
    date: "2026-03-06",
    tags: ["상부장 수리", "싱크대 리폼"],
  },
  {
    id: "case-041",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 파손, 리폼 교체 사례",
    region: "부평",
    summary: "상부장 파손, 리폼 교체 사례",
    beforeImg: "/images/cases/case-041-before.jpg",
    afterImg: "/images/cases/case-041-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224184145515",
    date: "2026-02-14",
    tags: ["상부장 수리", "상부장 처짐", "상부장 파손", "싱크대 리폼"],
  },
  {
    id: "case-040",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 처짐 수리 사례",
    region: "부천",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-040-before.jpg",
    afterImg: "/images/cases/case-040-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224215191203",
    date: "2026-03-13",
    tags: ["상부장 수리", "상부장 처짐"],
  },
  {
    id: "case-039",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "당구장 팔걸이 가죽 리폼 사례",
    region: "인천",
    summary: "가죽 리폼 사례",
    beforeImg: "/images/cases/case-039-before.jpg",
    afterImg: "/images/cases/case-039-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224304866033",
    date: "2026-06-03",
    tags: ["가죽 리폼", "의자 천갈이"],
  },
  {
    id: "case-038",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 처짐 수리 사례",
    region: "서울 강서구 화곡동",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-038-before.jpg",
    afterImg: "/images/cases/case-038-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224166325873",
    date: "2026-01-31",
    tags: ["상부장 수리", "상부장 처짐"],
  },
  {
    id: "case-037",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 처짐 수리 사례",
    region: "서울 사당",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-037-before.jpg",
    afterImg: "/images/cases/case-037-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224231352969",
    date: "2026-03-27",
    tags: ["상부장 수리", "상부장 처짐"],
  },
  {
    id: "case-036",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 처짐 수리 사례",
    region: "강서구 화곡동",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-036-before.jpg",
    afterImg: "/images/cases/case-036-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq/224274486122",
    date: "2026-05-4",
    tags: ["상부장 수리", "상부장 처짐"],
  },
  {
    id: "case-035",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 처짐 수리 사례",
    region: "광명",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-035-before.jpg",
    afterImg: "/images/cases/case-035-after.jpg",
    blogUrl: "https://blog.naver.com/restory99/224301324764",
    date: "2026-05-31",
    tags: ["상부장 수리", "상부장 처짐"],
  },
  {
    id: "case-034",
    category: "하부장 밑판 교체",
    parentCategory: "싱크대 수리",
    title: "곰팡이 때문에 하부장 밑판 교체 사례",
    region: "주안",
    summary: "휘어버린 하부장 밑판 교체 사례",
    beforeImg: "/images/cases/case-034-before.jpeg",
    afterImg: "/images/cases/case-034-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223714065910",
    date: "2026-05-31",
    tags: ["하부장", "밑판 교체", "지판 교체"],
  },
  {
    id: "case-033",
    category: "하부장 밑판 교체",
    parentCategory: "싱크대 수리",
    title: "하부장 밑판 교체 사례",
    region: "부평",
    summary: "휘어버린 하부장 밑판 교체 사례",
    beforeImg: "/images/cases/case-033-before.jpeg",
    afterImg: "/images/cases/case-033-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223508450821",
    date: "2026-05-30",
    tags: ["하부장", "밑판 교체", "지판 교체"],
  },
  {
    id: "case-031",
    category: "하부장 밑판 교체",
    parentCategory: "싱크대 수리",
    title: "하부장 밑판 교체 사례",
    region: "일산",
    summary: "물 먹어 부풀어 오른 하부장 밑판 교체 사례",
    beforeImg: "/images/cases/case-032-before.jpg",
    afterImg: "/images/cases/case-032-after.jpg",
    blogUrl: "https://blog.naver.com/restory99/224299421979",
    date: "2026-05-29",
    tags: ["하부장", "밑판 교체", "지판 교체"],
  },
  // ─── 기존 데이터 (원본 그대로) ────────────────────────────
  {
    id: "case-030",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "마포구 싱크대 상부장 처짐",
    region: "마포구",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-030-before.jpg",
    afterImg: "/images/cases/case-030-after.jpg",
    blogUrl: "https://blog.naver.com/restory99/224297244006",
    date: "2026-05-26",
    tags: ["싱크대 수리", "상부장 처짐"],
  },
  {
    id: "case-029",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "마포구 싱크대 상부장 처짐",
    region: "마포구",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-029-before.jpg",
    afterImg: "/images/cases/case-029-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224280849023",
    date: "2026-05-10",
    tags: ["싱크대 수리", "상부장 처짐"],
  },
  {
    id: "case-028",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "은평구 싱크대 상부장 처짐",
    region: "은평구",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-028-before.jpg",
    afterImg: "/images/cases/case-028-after.jpg",
    blogUrl: "https://blog.naver.com/restory99/224294684922",
    date: "2026-05-23",
    tags: ["싱크대 수리", "상부장 처짐"],
  },
  {
    id: "case-027",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "싱크대 상부장 처짐",
    region: "인천",
    summary: "상부장 처짐 수리 사례",
    beforeImg: "/images/cases/case-027-before.jpg",
    afterImg: "/images/cases/case-027-after.jpg",
    blogUrl: "https://blog.naver.com/restory99/224295909466",
    date: "2026-05-25",
    tags: ["싱크대 수리", "상부장 처짐"],
  },
  {
    id: "case-026",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "싱크대 문짝 리폼 사례",
    region: "당하동",
    summary: "깔끔한 화이트 톤으로 톤업!",
    beforeImg: "/images/cases/case-026-before.jpg",
    afterImg: "/images/cases/case-026-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224132059623",
    date: "2026-01-02",
    tags: ["싱크대 리폼", "문짝 교체"],
  },
  {
    id: "case-025",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "싱크대 상부장 처짐 수리 사례",
    region: "당하동",
    summary: "처지는 상부장 수리 완료!",
    beforeImg: "/images/cases/case-025-before.jpg",
    afterImg: "/images/cases/case-025-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224125798234",
    date: "2025-12-28",
    tags: ["싱크대 수리", "상부장 처짐"],
  },
  {
    id: "case-024",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "회사 중역 테이블 가죽 리폼 사례",
    region: "서울",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-024-before.jpg",
    afterImg: "/images/cases/case-024-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/224254978875",
    date: "2026-4-16",
    tags: ["가죽 리폼", "테이블 리폼"],
  },
  {
    id: "case-023",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "회사 의자 팔걸이 가죽 교체 사례",
    region: "인천",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-023-before.jpg",
    afterImg: "/images/cases/case-023-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/224252467099",
    date: "2026-4-14",
    tags: ["가죽 리폼", "의자 리폼"],
  },
  {
    id: "case-022",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "주방 문짝 리폼 사례",
    region: "인천",
    summary: "싱크대 리폼으로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-022-before.jpeg",
    afterImg: "/images/cases/case-022-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223627902056",
    date: "2025-10-21",
    tags: ["싱크대 리폼", "주방 리폼"],
  },
  {
    id: "case-021",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 주방 문짝 리폼 사례",
    region: "인천 신현동",
    summary: "싱크대 리폼으로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-021-before.jpeg",
    afterImg: "/images/cases/case-021-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223561594571",
    date: "2025-08-26",
    tags: ["싱크대 리폼", "주방 리폼"],
  },
  {
    id: "case-020",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 싱크대 리폼 사례",
    region: "인천 신현동",
    summary: "싱크대 리폼으로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-020-before.jpeg",
    afterImg: "/images/cases/case-020-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223721448726",
    date: "2026-01-10",
    tags: ["싱크대 리폼", "주방 리폼"],
  },
  {
    id: "case-019",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 싱크대 리폼 사례",
    region: "인천 주안",
    summary: "싱크대 리폼으로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-019-before.jpeg",
    afterImg: "/images/cases/case-019-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223853692269",
    date: "2026-05-19",
    tags: ["싱크대 리폼", "주방 리폼"],
  },
  {
    id: "case-018",
    category: "소파 복원",
    parentCategory: "소파 복원",
    title: "인천 소파 수리 사례",
    region: "인천 주안",
    summary: "소파 내부 스프링 문제 해결",
    beforeImg: "/images/cases/case-018-before.jpeg",
    afterImg: "/images/cases/case-18-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1515-/223870415860",
    date: "2026-05-19",
    tags: ["소파수리", "소파복원", "스프링보강"],
  },
  {
    id: "case-017",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 싱크대 문짝 리폼",
    region: "인천 부평구",
    summary: "싱크대 문짝 리폼으로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-017-before.jpg",
    afterImg: "/images/cases/case-017-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/223944501024",
    date: "2026-01-18",
    tags: ["싱크대 문짝", "싱크대리폼"],
  },
  {
    id: "case-016",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "인천 싱크대 상부장 처짐",
    region: "인천 서구",
    summary: "싱크대 상부장 처짐 수리",
    beforeImg: "/images/cases/case-016-before.jpg",
    afterImg: "/images/cases/case-016-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/224151250245",
    date: "2026-01-18",
    tags: ["싱크대 상부장 처짐", "싱크대수리"],
  },
  {
    id: "case-015",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "사우나 의자 가죽 리폼",
    region: "그랜드 cc",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-015-before.jpg",
    afterImg: "/images/cases/case-015-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/224261704874",
    date: "2026-04-22",
    tags: ["가죽교체   ", "밴치 가죽 리폼"],
  },
  {
    id: "case-014",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "회의 테이블 가죽 교체",
    region: "서울",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-014-before.jpg",
    afterImg: "/images/cases/case-014-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-/224282231613",
    date: "2026-05-11",
    tags: ["가죽교체   ", "테이블 리폼"],
  },
  {
    id: "case-013",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "양천구 목동 의자 가죽 리폼",
    region: "서울 양천구",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-013-before.jpg",
    afterImg: "/images/cases/case-013-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224150440262",
    date: "2026-01-18",
    tags: ["가죽교체   ", "테이블 리폼"],
  },
  {
    id: "case-012",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "강서구 회사 중역 테이블 가죽 리폼",
    region: "서울 강서구",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-012-before.jpg",
    afterImg: "/images/cases/case-012-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224155220771",
    date: "2026-01-22",
    tags: ["가죽교체   ", "테이블 리폼"],
  },
  {
    id: "case-011",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "관악구 가죽 리폼",
    region: "서울 관악구",
    summary: "가죽 리폼으로 새로운 공간 분위기 연출",
    beforeImg: "/images/cases/case-011-before.jpg",
    afterImg: "/images/cases/case-011-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224167034363",
    date: "2026-02-01",
    tags: ["가죽교체", "의자 리폼"],
  },
  {
    id: "case-010",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "관악구 싱크대 문짝 리폼",
    region: "서울 관악구",
    summary: "싱크대 문짝만 교체로 새로운 주방",
    beforeImg: "/images/cases/case-010-before.jpeg",
    afterImg: "/images/cases/case-010-after.jpeg",
    blogUrl: "https://blog.naver.com/kohh1115/224229109558",
    date: "2026-03-25",
    tags: ["문짝 교체", "싱크대 리폼"],
  },
  {
    id: "case-009",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "인천 싱크대 문짝 리폼",
    region: "인천",
    summary: "싱크대 문짝만 교체로 새로운 주방 느낌",
    beforeImg: "/images/cases/case-009-before.jpg",
    afterImg: "/images/cases/case-009-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115/224259313207",
    date: "2026-04-20",
    tags: ["문짝 교체", "싱크대 리폼"],
  },
  {
    id: "case-001",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "인천 서구 상부장 처짐 수리",
    region: "인천 서구",
    summary:
      "상부장 경첩이 빠져서 문짝이 처진 상태. 경첩 교체 + 프레임 보강으로 당일 완료.",
    beforeImg: "/images/cases/case-001-before.jpg",
    afterImg: "/images/cases/case-001-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq",
    date: "2026-05-10",
    tags: ["상부장", "경첩", "당일수리"],
  },
  {
    id: "case-002",
    category: "상부장 처짐",
    parentCategory: "싱크대 수리",
    title: "상부장 추락 사례",
    region: "부천 작동",
    summary: "서랍이 안 닫히는 증상. 레일 부식으로 3단 서랍레일 전체 교체.",
    beforeImg: "/images/cases/case-002-before.jpg",
    afterImg: "/images/cases/case-002-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq",
    date: "2026-05-08",
    tags: ["상부장", "추락", "부식"],
  },
  {
    id: "case-003",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "경기 부천시 주방 문짝 전체 교체",
    region: "경기 부천시",
    summary:
      "20년 된 주방 문짝 색상 변색. 본체는 그대로 두고 문짝만 42장 교체.",
    beforeImg: "/images/cases/case-003-before.jpg",
    afterImg: "/images/cases/case-003-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115",
    date: "2026-05-05",
    tags: ["문짝교체", "변색", "리폼"],
  },
  {
    id: "case-004",
    category: "싱크대 리폼",
    parentCategory: "싱크대 리폼",
    title: "서울 강서구 싱크대 상판 + 문짝 리폼",
    region: "서울 강서구",
    summary:
      "상판 스크래치 심하고 문짝 들뜸. 상판 교체 + 문짝 리폼으로 새 주방 느낌.",
    beforeImg: "/images/cases/case-004-before.jpg",
    afterImg: "/images/cases/case-004-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1115",
    date: "2026-04-28",
    tags: ["상판", "스크래치", "리폼"],
  },
  {
    id: "case-005",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "강남 레스토랑 의자 30개 천갈이",
    region: "서울 강남구",
    summary: "가죽 벗겨진 레스토랑 의자 30개. 영업 중 작업으로 하루 만에 완료.",
    beforeImg: "/images/cases/case-005-before.jpg",
    afterImg: "/images/cases/case-005-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-",
    date: "2026-04-25",
    tags: ["레스토랑", "천갈이", "대량"],
  },
  {
    id: "case-006",
    category: "가죽 리폼",
    parentCategory: "가죽 리폼",
    title: "카페 소파 부스석 가죽 교체",
    region: "경기 일산",
    summary: "10년 된 카페 부스석 가죽 갈라짐. 인조가죽으로 전체 교체.",
    beforeImg: "/images/cases/case-006-before.jpg",
    afterImg: "/images/cases/case-006-after.jpg",
    blogUrl: "https://blog.naver.com/kohh1515-",
    date: "2026-04-20",
    tags: ["카페", "부스석", "인조가죽"],
  },
  {
    id: "case-007",
    category: "소파 복원",
    parentCategory: "소파 복원",
    title: "인천 송도 3인 소파 꺼짐 복원",
    region: "인천 송도",
    summary:
      "소파 쿠션 꺼짐이 심해서 앉으면 바닥 느낌. 내부 스프링 + 고밀도 폼 보강.",
    beforeImg: "/images/cases/case-007-before.jpg",
    afterImg: "/images/cases/case-007-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq",
    date: "2026-04-15",
    tags: ["쿠션꺼짐", "스프링", "폼보강"],
  },
  {
    id: "case-008",
    category: "소파 복원",
    parentCategory: "소파 복원",
    title: "서울 마포구 가죽소파 꺼짐 복원",
    region: "서울 마포구",
    summary: "소파 꺼짐 심해서 앉으면 바닥 느낌. 내부 스프링 + 고밀도 폼 보강.",
    beforeImg: "/images/cases/case-008-before.jpg",
    afterImg: "/images/cases/case-008-after.jpg",
    blogUrl: "https://blog.naver.com/sofaresq",
    date: "2026-04-10",
    tags: ["가죽소파", "꺼짐", "복원"],
  },
];
